### PR TITLE
[2/n] fix! add abortableFetch polyfill to fix bug

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

This fixes an error that seems to arise when running queries in next APIs locally. I am unsure if it happens in prod.

Error is:
```
Error: The "emitter" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
```

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3194** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3194" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3194?utm_source=stack-comment).

**Comment by tomquirk** [comment]
@wraeth-eth could you give some context here? 🙏

**Comment by tomquirk** [comment]
closing for now based on discord DMs!

**Comment by wraeth-eth** [comment]
@tomquirk Hey i'm going to re-open this (hope its okay), and mark it as draft. Due to the way that graphite works this will delete it from my local which is not what I want as I have other work built on top of this locally

**Comment by wraeth-eth** [comment]
Closing as this seems to be an error with v19.xx of Node. Rolling back to node 16 alleviates problem

**Pull request closed without merging**
