### PR TITLE
[8/x] Add label truncation for long numbers

### PR DESCRIPTION
**Pull request by jmilldotdev**
## What does this PR do and why?

Adds a fancy function to display long numbers using K, M, B, T notation, ie 100K, 2M, 5B

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by jmilldotdev** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1586** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1586" target="_blank">Graphite</a> 
    * **PR #1587** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1587" target="_blank">Graphite</a> 
      * **PR #1588** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1588" target="_blank">Graphite</a> 
        * **PR #1594** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1594" target="_blank">Graphite</a> 
          * **PR #1595** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1595" target="_blank">Graphite</a> 
            * **PR #1596** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1596" target="_blank">Graphite</a> 
              * **PR #1597** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1597" target="_blank">Graphite</a> 
                * **PR #1598** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1598" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1598?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]

**Comment by jmilldotdev** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1598?utm_source=stack-comment).


Job Reference: 5peKCVtRG7hIeC6BSrBI

**Comment by jmilldotdev** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1598?utm_source=stack-comment).


Job Reference: 0agyc4HkFZeecGjH4TTU

**Comment by jmilldotdev** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1598?utm_source=stack-comment).


Job Reference: I3QazDznUYZOKiV2bxLz

**Pull request merged**
