### PR TITLE
Add cursor pointer for filters label

### PR DESCRIPTION
**Pull request by edizyurdakul**
## What does this PR do and why?

Fixes issue #883
https://github.com/jbx-protocol/juice-interface/issues/883

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the
changes._

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Review by wraeth-eth — APPROVED** [review]
LGTM 👍

**Review by johnnyd-eth — APPROVED** [review]

**Comment by johnnyd-eth** [comment]
LFG @edizyurdakul merging

**Comment by johnnyd-eth** [comment]
Also @edizyurdakul if you add the word 'Closes' before the issue number it will close the issue automatically when merged 👯

**Comment by edizyurdakul** [comment]
> Also @edizyurdakul if you add the word 'Closes' before the issue number in the description Github will close the issue automatically when merging the PR 👯

Oh thanks, didn't know that I am new to contributions(pulling and stuff) in GitHub, thank you.

**Pull request merged**
