### PR TITLE
Refactor email notification handling in on-pay event [5/n]

### PR DESCRIPTION
**Pull request by wraeth-eth**
## Description

This PR optimizes the email notification handling in the `on-pay` event to enhance performance and simplify the code. The main changes include:

1. Remove the use of the GraphQL `ParticipantsDocument` query and the associated `client.query()` call. Instead, we directly fetch user data with the necessary subscription information from the `users` table in the Supabase database.
2. Update the `usersResult` query to include `user_subscriptions` with `project_id` and `notification_id` in the `select` statement. The filtering for relevant users and their subscriptions is now done post-query.
3. The `orQuery` has been removed and replaced with a filter operation applied after the query execution. The filter operation includes users who are either subscribed to the project or are the payer.
4. Map the filtered users to the appropriate email event type based on their wallet.

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] (if relevant) I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] (if relevant) I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3317** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3317" target="_blank">Graphite</a> 
    * **PR #3318** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3318" target="_blank">Graphite</a> 
      * **PR #3319** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3319" target="_blank">Graphite</a> 
        * **PR #3321** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3321" target="_blank">Graphite</a> 
          * **PR #3325** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3325" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3325?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]

**Comment by wraeth-eth** [comment]
@wraeth-eth queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3325).

**Comment by wraeth-eth** [comment]
[Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3325) couldn't merge this pull request because a downstack PR #3319 failed to merge.

**Comment by wraeth-eth** [comment]
@wraeth-eth queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3325).

**Comment by wraeth-eth** [comment]
@wraeth-eth merged this pull request with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3325).

**Pull request merged**
