### PR TITLE
A bunch of random V2 create fixes

### PR DESCRIPTION
**Pull request by aeolianeth**
## What does this PR do and why?

This PR is big and sweeping, sorry. But the main thing it fixes is the Tokens tab, as well as adds complete unit test coverage of our V2 math utils, and also uses these utils in a better way throughout.

I don't have time to add comments to this PR, hoping for your trust in the code, and probably best to just test the feature and let me know if anything is sus.

**Note** on UX, I've removed some of the opinionated defaults for form values (like reserved rate and discount rate). I think this is for the best, or at the least, it reduces complexity and bug risk in the implementation. If you feel strongly about keeping it lets chat in discord.

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Comment by johnnyd-eth** [comment]
Nice @aeolianeth. Got a few comments, but if you want to make an issue of them and we get to them in a follow up.

Screen Shot 2022-04-14 at 12 21 13 pm

- Discount rate should be disabled when funding duration is 0
- When reserved rate is enabled, value should go to 50% I think. Not 0

Screen Shot 2022-04-14 at 12 24 44 pm

- 'Disabled when no funding target is set.' remains after funding target has been set

- **Praise**: nice fix of the duration and time until next funding cycle
- **Question:** why are the switches removed from discount rate and redemption rate fields?
- **Idea:** maybe we should add a sentence in the token tab, something like, 'Once your project is deployed you can launch your own ERC20 token with a custom name and code (e.g. DOGE)'

**Comment by aeolianeth** [comment]
@johnnyd-eth 

Let's do these ones: 
- Discount rate should be disabled when funding duration is 0
- 'Disabled when no funding target is set.' remains after funding target has been set

Let's leave everything else as-is for now. I'm concerned these forms are too complex from both UX and implementation PoV. We can push back on the design mockups where it makes sense to, and improve later on. Simple means we can iterate faster.

**Comment by johnnyd-eth** [comment]
> 

@aeolianeth ok I've fixed and pushed fixes to those 2 points. Happy to merge this now?

**Review by johnnyd-eth — APPROVED** [review]

**Comment by johnnyd-eth** [comment]
Screen Shot 2022-04-14 at 2 03 13 pm

- When discount rate disabled, should be either hide the slider or set it 0%? Personally would prefer hiding the sliders (in disabled redemp rate as well) because the 0% and 100% are meaningless in these disabled states

**Pull request merged**
