### PR TITLE
Styling regression fixes

### PR DESCRIPTION
**Pull request by tomquirk**
## What does this PR do and why?

- fix pay input margin
- fix social links on mobile

## Screenshots or screen recordings

| before | after |
| --- | --- |
| Screen Shot 2022-07-27 at 10 13 48 AM | Screen Shot 2022-07-27 at 10 10 37 AM |
| Screen Shot 2022-07-27 at 10 12 48 AM | Screen Shot 2022-07-27 at 10 10 49 AM |

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [x] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by tomquirk** [comment]
@jmilldotdev down to review this small one?

**Review by jmilldotdev — APPROVED** [review]
LGTM, though for the social links wondering if there's some way we could get it all on a single line on mobile...maybe icons only?

**Comment by tomquirk** [comment]
> LGTM, though for the social links wondering if there's some way we could get it all on a single line on mobile...maybe icons only?

Hmm yeah fair point. Wondering if there is enough touch area though...

cc @strath-m in case you have thots

**Comment by strath-m** [comment]
Might be a bit late but you could for sure have it like this. Small clickable icons. It's a familiar mental model, especially in this space and helps tidy it up and bring it all onto one line.

Screen Shot 2022-07-27 at 4 29 15 pm

**Comment by tomquirk** [comment]
@strath-m oh yeahhhhh, love it https://github.com/jbx-protocol/juice-interface/issues/1565

**Pull request merged**
