### PR TITLE
Add dropdowns to project create flow

### LINKED ISSUE #1288: Add dropdowns to project details section in create flow
## Description

Screen Shot 2022-06-27 at 12 12 27 pm

## Proposal

Use the `MinimalCollapse` component (probably).

## Screenshots

_If applicable, add screenshots to help explain your problem._

### PR DESCRIPTION
**Pull request by jmilldotdev**
## What does this PR do and why?

Closes #1288. Uses MinimalCollapse component to reduce amount of information a user is presented with on creating a project.

## Screenshots or screen recordings

Collapsed state:

image

Uncollapsed:

image

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by aeolianeth** [comment]
@jmilldotdev nice!

WDYT about making the headers themselves collapsible? Might not be able to use `MinimalCollapse` out of the box, not sure.

**Comment by aeolianeth** [comment]
Another potential option. The header here would be click-able, too. Not sure...

Screen Shot 2022-07-05 at 9 08 26 PM

**Comment by jmilldotdev** [comment]
cool, is there a component for this?

**Comment by aeolianeth** [comment]
> cool, is there a component for this?

```html
<MinimalCollapse header={<h3 style={{ marginBottom: 0 }}>Links</h3>} />
```

**Comment by jmilldotdev** [comment]
image

**Review by aeolianeth — APPROVED** [review]
@jmilldotdev awesome shit. looks great to me.

Merging.

**Pull request merged**
