### PR TITLE
[1/n] fix! Rebuild mobile navigation from ground up

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

There was some formatting fudging, as well as just ant design behaving irregularly, so I rebuilt in pure css and used headless ui.

This work was required to fix the update branding on mobile

### Before

Screen Shot 2023-03-15 at 12 21 17 pm

### After

Screen Shot 2023-03-15 at 12 22 03 pm

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3215** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3215" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3215?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]
FUCK YES. You legend!!!!

**Comment by wraeth-eth** [comment]
@wraeth-eth queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3215).

**Comment by wraeth-eth** [comment]
@wraeth-eth merged this pull request with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3215).

**Pull request merged**
