### PR TITLE
Add Podcast link to navbar

### PR DESCRIPTION
**Pull request by nnnnicholas**
## What does this PR do and why?
Adds Podcast link to navbar

Attempted to rebase. Not sure if I did this correctly. 

## Acceptance checklist
- [x ] I have evaluted the [Approval Guidelines](../../CONTRIBUTING.md#approval-guidelines) for this PR.

### CODE REVIEW

**Comment by peripheralist** [comment]
nice! for most people this is just going to link to a Notion login screen. maybe we should link to Spotify instead? @nnnnicholas

**Comment by nnnnicholas** [comment]
@peripheralist Ah, good call. I forgot that one cannot see the Notion without an account -- perhaps this was different in the past.. 

I hate to choose favorites between the podcasting platforms. I'll swap for Spotify for now, and we can swap for a Juicebox Podcast subscription page something like http://web3galaxybrain.com when we're ready.

**Comment by peripheralist** [comment]
it'd be awesome to build a dedicated podcast page into the app with links to Spotify/etc, and maybe even an in-browser player. i'm down to just include a platform link for now

**Comment by nnnnicholas** [comment]
Updated with Spotify link! @peripheralist

**Comment by peripheralist** [comment]
...how on earth did https://github.com/jbx-protocol/juice-interface/pull/319 get merged into here? @aeolianeth am i missing something

**Comment by aeolianeth** [comment]
> ...how on earth did #319 get merged into here? @aeolianeth am i missing something

😬 This looks like a rebase gone a bit wonky. A squash-and-merge will probably work, but I imagine if we rebase again from the latest main, and resolve the conflicts, everything will sort itself out.

@nnnnicholas @peripheralist happy to record a video of the process and share it here async. LMK ❤️

**Comment by nnnnicholas** [comment]
I was confused by this too @peripheralist @aeolianeth. 

I think I hit Undo Commit by accident and it undid #319 somehow. At the time I deleted my local copy of juice-interface and cloned anew, but it seems it didn't fix the problem. 

I'm not sure what do to in a circumstance like this. [I see that I can](https://stackoverflow.com/questions/48283356/how-to-redo-an-undo-most-recent-commit-in-github-desktop) `git reflog` and `git reset #######`. I've tried `git reset 88177fd`, the latest commit to main, then pushing changes to podcast branch. I think this just made it worse. Maybe I should just redo the podcast navbar change in a new branch. Sorry.

**Comment by aeolianeth** [comment]
@nnnnicholas don't worry - it happens to me on a weekly basis probably 😅 .

There's probably some git magic out there to help, but sometimes the easiest solution is to start over. In this case, that's probably what I'd do: create a new branch, copy the changes across (like, literally copy-paste the code you want from this PR), and submit a new PR.

Totally valid solution and don't let anyone tell you otherwise 🤣

**Comment by peripheralist** [comment]
gonna close this since i think @johnnyd-eth will handle adding this with the new navbar formatting. thanks @nnnnicholas !

**Pull request closed without merging**
