### PR TITLE
Fix memo saving on transaction cancel

### PR DESCRIPTION
**Pull request by NakedFool**
## What does this PR do and why?
Closes https://github.com/jbx-protocol/juice-interface/issues/2773
Closes https://github.com/jbx-protocol/juice-interface/issues/2815

The issues were discovered while working on each other and they are related. The main fix is that memo data and stickerUrls are now properly saved when a transaction is canceled. Additionally, the radio button that toggles the beneficiary address is now also saved.

The PR also addresses an issue with the inclusion of NFT rewards in the initial stickerUrls array by:

- passing the nftRewardTiers as state to the V2V3PayForm component to prevent re-rendering.

- in the V2V3PayForm hook, it checks if the form already has values. If the form does not have values, it proceeds to set the initialized NFT stickers. If the form already has values, the function exits and the existing values are preserved, allowing them to be saved when the user cancels the transaction.

## Screenshots or screen recordings

https://user-images.githubusercontent.com/18723426/213181664-b62fdf86-ebb5-4c20-92ad-a0355d29095c.mov

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by tomquirk** [comment]
@wraeth-eth mind reviewing?

**Comment by wraeth-eth** [comment]
Hey @NakedFool thanks for the PR. This still has a problem where the memo is empty ("") after clicking pay after rejecting once.

Steps to repeat
1. Open a pay modal
2. Add some stickers to the memo
3. Click Pay
4. Note that the transaction is properly built in the console output
5. Cancel Transaction
6. Immediately click pay again
7. Note that the transaction memo is empty ("") in console output

**Comment by wraeth-eth** [comment]
FWIW I think we should try to limit adding more `useEffect` where possible as these initial bugs are likely due to `useEffect`. It is probably out of scope for this though. If you can get it working with its current solution. If not, I'd recommend looking to incrementally pare back the useEffects used in this modal (while retaining same behavior), then fix the bugs.

**Comment by wraeth-eth** [comment]
@NakedFool I was pretty vague, lemme know if you wanna try and organise some time in cross over to chat about it further if you want!

**Comment by NakedFool** [comment]
> 

Hmmm, how so ser? I've just tried to do it one more time again, attaching a video, soz its is a bit long ~ 1min 🍿 


https://user-images.githubusercontent.com/18723426/214235807-a987c66f-7bba-4d80-8a61-efd06f99099b.mov

**Comment by NakedFool** [comment]
> Hey @NakedFool thanks for the PR. This still has a problem where the memo is empty ("") after clicking pay after rejecting once.
> 
> Steps to repeat
> 
> 1. Open a pay modal
> 2. Add some stickers to the memo
> 3. Click Pay
> 4. Note that the transaction is properly built in the console output
> 5. Cancel Transaction
> 6. Immediately click pay again
> 7. Note that the transaction memo is empty ("") in console output

Hmmm, how so ser? I've just tried to do it one more time again, attaching a video, soz its is a bit long ~ 1min 🍿


https://user-images.githubusercontent.com/18723426/214236279-f6a7463f-875c-424c-9323-fc9a7b3bd220.mov

**Comment by NakedFool** [comment]
> FWIW I think we should try to limit adding more `useEffect` where possible as these initial bugs are likely due to `useEffect`. It is probably out of scope for this though. If you can get it working with its current solution. If not, I'd recommend looking to incrementally pare back the useEffects used in this modal (while retaining same behavior), then fix the bugs.

Yeah, I feel you.

In general, I agree with you that we should utilize as less effects as possible because of their risky behaviors and less error-prone situations in the future, but I think this case was specific and it deserves more attention.

I think the problem here is `V2V3PayForm` component since we are passing `nftRewardTiers` from there, and in a real scenario, that initial useEffect in `V2V3ConfirmPayModal` should only run once when `nftRewardTiers` is passed, but it was re-rendering constantly before due to what I think the way of defining it in `V2V3PayForm`.

Thank you for this review, I'm really down to organize some time and go over this quickly together! 🍻

**Comment by wraeth-eth** [comment]
> > Hey @NakedFool thanks for the PR. This still has a problem where the memo is empty ("") after clicking pay after rejecting once.
> > Steps to repeat
> > 
> > 1. Open a pay modal
> > 2. Add some stickers to the memo
> > 3. Click Pay
> > 4. Note that the transaction is properly built in the console output
> > 5. Cancel Transaction
> > 6. Immediately click pay again
> > 7. Note that the transaction memo is empty ("") in console output
> 
> Hmmm, how so ser? I've just tried to do it one more time again, attaching a video, soz its is a bit long ~ 1min 🍿
> 
>  screen-recorder-tue-jan-24-2023-08-28-59.mov

Ah I know the difference, make sure you don't have an NFT. This also creates some problems if you remove an NFT too.


https://user-images.githubusercontent.com/104132113/214972415-a34aff36-21bf-44b1-b815-5685b78be3a2.mov

**Comment by NakedFool** [comment]
> > > Hey @NakedFool thanks for the PR. This still has a problem where the memo is empty ("") after clicking pay after rejecting once.
> > > Steps to repeat
> > > 
> > > 1. Open a pay modal
> > > 2. Add some stickers to the memo
> > > 3. Click Pay
> > > 4. Note that the transaction is properly built in the console output
> > > 5. Cancel Transaction
> > > 6. Immediately click pay again
> > > 7. Note that the transaction memo is empty ("") in console output
> > 
> > 
> > Hmmm, how so ser? I've just tried to do it one more time again, attaching a video, soz its is a bit long ~ 1min 🍿
> > screen-recorder-tue-jan-24-2023-08-28-59.mov
> 
> Ah I know the difference, make sure you don't have an NFT. This also creates some problems if you remove an NFT too.
> 
>  Untitled.mov

Oo gotcha, I think I've got it working all correctly now, mainly operating on `transactionCanceled` value which is called when a user cancels the transaction.


https://user-images.githubusercontent.com/18723426/215486754-4f8e92d6-0e68-489e-907a-b1030844440c.mov

**Review by wraeth-eth — APPROVED** [review]
Approving - still highly suspect on all the useEffect we have near this code though 😬

**Comment by wraeth-eth** [comment]
Found another bug - but it already existed. Will make a new ticket for it.

Good work on this one @NakedFool !

**Pull request merged**
