### PR TITLE
Move wallet sign in into separate hook [2/n]

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

This PR refactors the account dashboard component and introduces the useWalletSignIn hook to simplify the wallet sign-in process.

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] (if relevant) I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] (if relevant) I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3317** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3317" target="_blank">Graphite</a> 
    * **PR #3318** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3318" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3318?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]
nice cleanup!

**Comment by wraeth-eth** [comment]
@wraeth-eth queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3318).

**Comment by wraeth-eth** [comment]
@wraeth-eth merged this pull request with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3318).

**Pull request merged**
