### PR TITLE
feat: legal resources page

### PR DESCRIPTION
**Pull request by filipviz**

### CODE REVIEW

**Comment by filipviz** [comment]
Q for @tomquirk – do you think it's worth translating this page? I think it might make sense to leave things in English for now.

**Comment by tomquirk** [comment]
@filipviz agreed

**Comment by filipviz** [comment]
Awaiting Rob's review (from [Open Esquire](https://openesq.tech/)). Keeping as a draft for now.

**Comment by filipviz** [comment]
See feedback discussion on [Discord](https://discord.com/channels/775859454780244028/1120513423306915870/1120513428797272084).

**Comment by filipviz** [comment]
Changes approved by Rob in [this message](https://discord.com/channels/775859454780244028/1120513423306915870/1126219689475965039). Ready to merge.

**Review by peripheralist — APPROVED** [review]

**Pull request merged**
