### PR TITLE
Add quick search button to navbar

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2688** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2688" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2688?utm_source=stack-comment).

**Comment by johnnyd-eth** [comment]
@wraeth-eth is this ready for review?

**Comment by johnnyd-eth** [comment]
This is so good @wraeth-eth, awesome feature. A few initial comments:

- I'm not sure pressing enter should trigger the modal to close. I instinctively pressed enter after typing the handle and nothing had loaded so it just closed. 
- 
- Arrow slightly off-centre vertically here:
Screen Shot 2022-12-15 at 12 57 23 pm

- The close button in the top-left feels a bit counter-intuitive to me. WDYT about moving it to the top-right in the same position as the other modals? cc @strath-m 

- For accessibility purposes, could we get the whole row acting as a link (just as the project handle is doing - showing link in the bottom left, etc.)

**Review by johnnyd-eth — CHANGES_REQUESTED** [review]
.

**Comment by wraeth-eth** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2688?utm_source=stack-comment).


Job Reference: 2bAUhs2EHCJP9ndbxt1e

**Pull request merged**
