### PR TITLE
Add tools drawer to new v2v3 dashboard

### PR DESCRIPTION
**Pull request by peripheralist**
image
image

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Awesome PR!! 



looks like the button is mis-matched in dark mode

**Comment by wraeth-eth** [comment]
It is also missing on mobile, but that might be intentional

**Review by wraeth-eth — CHANGES_REQUESTED** [review]
above comments 🙏

**Comment by peripheralist** [comment]
thanks @wraeth-eth , fixed.

**Review by wraeth-eth — APPROVED** [review]

**Pull request merged**
