### PR TITLE
feat/project-metadatas

### PR DESCRIPTION
**Pull request by palevoo**
So with this PR when people share link of their project's page, metadata for preview on the web (discord, twitter, telegram), should show information specific to the project instead of generic Juicebox one, as well as in the tab title they will see the dao name too.

I've used existing metadata from project such as name, description, logoUrl and twitter. In future we could further improve this by creating auto-generated preview images from provided project info

### CODE REVIEW

**Comment by peripheralist** [comment]
so stoked on this. @palevoo could you add a description here explaining what we're looking at?

**Review by odd-amphora — CHANGES_REQUESTED** [review]
Let's make sure we get a working preview before this is merged. But super great work on getting this started!

**Comment by peripheralist** [comment]
@palevoo from your recent discord post it sounds like this isn't going to work as expected? should we leave this open?

**Comment by palevoo** [comment]
@peripheralist yep, that is true, I'm still looking around into possible workarounds, will close this one if don't come up with anything, in meantime I've opened a PR #213 with only updating client side `document.tile` with project's name

**Comment by peripheralist** [comment]
this relates to #145

**Comment by peripheralist** [comment]
closing this since we're now exploring other options for supporting custom project page meta tags

**Pull request closed without merging**
