### PR TITLE
added shared component for prefix inputs

### PR DESCRIPTION
**Pull request by NakedFool**
## What does this PR do and why?

Fixes - https://github.com/jbx-protocol/juice-interface/issues/2157

I've added shared component `PrefixInput` (the name may be dumb but please suggest if you have a better one 😺 ) that is going to handle all inputs that need prefixes throughout the app.

The first example was in the creation flow, therefore I first adjusted in NFT rewards input that is responsible for external links ( you gonna see in the video ), and then I've added prefix input in details for project links.

one note: CSS is acting weird in project links, @wraeth-eth do you have any idea since this is your baby? 🙏 

Small touchups: 

- created `url.ts` and moved functions over from `SocialLinks.tsx` so we can use them everywhere such as -  `prettyUrl` , `linkUrl`
-  adjusted `prettyUrl` function a bit, now we also remove slash at the end of URL, for example in past we displayed `example.com/` and now we display `example.com`

## **Before**

https://user-images.githubusercontent.com/18723426/199320841-979a325f-a84d-403d-a7ba-59415b4373af.mov

## **After**

https://user-images.githubusercontent.com/18723426/199320869-92b736e2-6679-480b-8ac4-580e7a04bbe1.mov

image

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by johnnyd-eth** [comment]
This is great @NakedFool. I think maybe we could change the name to `PrefixedInput`. I also think the default value 'https' is probably unnecessary, and we should just require giving it as the `prefix` prop in each instance of the component. Looks great to me otherwise.

**Review by johnnyd-eth — CHANGES_REQUESTED** [review]
.

**Comment by NakedFool** [comment]
> This is great @NakedFool. I think maybe we could change the name to `PrefixedInput`. I also think the default value 'https' is probably unnecessary, and we should just require giving it as the `prefix` prop in each instance of the component. Looks great to me otherwise.

Fixed conflict and applied changes ser!

**Comment by tomquirk** [comment]
@johnnyd-eth @NakedFool shall we get this merged?

**Comment by NakedFool** [comment]
> @johnnyd-eth @NakedFool shall we get this merged?

it looks good to me now, there was a minor conflict with importing stuff but now that's resolved.

**Review by johnnyd-eth — APPROVED** [review]
Whoops my bad for lagging on this one! LGTM

**Pull request merged**
