### PR TITLE
Add "I accept terms of service" to project creation form.

### PR DESCRIPTION
**Pull request by tomquirk**
## What does this PR do and why?

- Adds "accept terms" checkbox to project creation flow
- Adds terms of service link to footer

## Screenshots or screen recordings

| default | invalid | footer |
| --- | --- | --- |
| Screen Shot 2022-07-29 at 11 16 59 PM | Screen Shot 2022-07-29 at 11 17 04 PM | Screen Shot 2022-07-29 at 11 18 04 PM |

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [x] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by tankbottoms** [comment]
Per note in Discord, I was  wrong, there is case law that requires site to notify users affirmatively that the [Terms of Service](https://juicebox-legal.on.fleek.co/user/legal/Juicebox/tos) has been updated so we do have to have click box, apologies, I was totally wrong. So what is pictured suffices and [this](https://juicebox-legal.on.fleek.co/user/legal/Juicebox/tos) is the latest which @filipv-eth will likely move from this directory but perhaps he could host somewhere you can access it consistently?

**Comment by filipv-eth** [comment]
I have migrated the ToS to [https://info.juicebox.money/tos/](https://info.juicebox.money/tos/), and will be publishing further revisions at that URL.

**Comment by tomquirk** [comment]
Awesome thanks @tankbottoms @filipv-eth . Link updated!! ❤️ 

@johnnyd-eth could you pls review this when you have the chance?

**Comment by johnnyd-eth** [comment]
Killed it @tankbottoms @filipv-eth. 

LGTM @aeolianeth although might need to get some wrapping going in the mobile footer:

Screen Shot 2022-07-30 at 2 38 12 pm

**Review by johnnyd-eth — CHANGES_REQUESTED** [review]
(mobile footer links need wrap)

**Comment by tomquirk** [comment]
@johnnyd-eth ah nice nice catch, fixed:

Screen Shot 2022-07-30 at 3 23 24 PM

**Review by johnnyd-eth — APPROVED** [review]
Perfect, LGTM

**Pull request merged**
