### PR TITLE
Add tooltips to buttons

### LINKED ISSUE #889: Add Tooltips on 'Tools' and 'Reconfigure' buttons
## Description

Tooltips on the 2 buttons on the right here. 

Screen Shot 2022-04-30 at 2 37 26 pm

On hover: Wrench should show 'Tools',  Cog should show 'Reconfigure project and funding details'

Let's do **for both V1 and V2**

## Screenshots

_If applicable, add screenshots to help explain your problem._

### PR DESCRIPTION
**Pull request by jmilldotdev**
## What does this PR do and why?

Closes #889 

## Screenshots or screen recordings

image

## Acceptance checklist

- [ x ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ x ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Comment by johnnyd-eth** [comment]
Nice @jmilldotdev just mark these ones for translations and commit the new `.po` files and we'll be good to merge

**Comment by jmilldotdev** [comment]
> Nice @jmilldotdev just mark these ones for translations and commit the new `.po` files and we'll be good to merge

Done

**Comment by johnnyd-eth** [comment]
Nice @jmilldotdev LGTM! Merging

**Comment by johnnyd-eth** [comment]
Also P.S. adding 'closes' before the issue number in the Github description closes the issue when PR is merged

**Review by johnnyd-eth — APPROVED** [review]

**Pull request merged**
