### PR TITLE
[Feature] veBanny NFT Staking

### PR DESCRIPTION
**Pull request by jmilldotdev**
## What does this PR do and why?

Now that I am onboarded as a contributor, I am PRing the work i did in my fork on the veBanny NFT staking feature to the main repo. This will exist as a feature branch, and I will PR into it as I refine the design. The functionality is mostly complete other than reading data from the veBanny contracts.

## Screenshots or screen recordings

https://forested-petunia-b18.notion.site/veBanny-44790d9f0c4e4aad8b0f1e94a3477c80

## Acceptance checklist

- [ x ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ x ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Comment by aeolianeth** [comment]
@jmilldotdev does it make sense to close this PR for now?

**Comment by jmilldotdev** [comment]
I think so, it doesn't seem like this code will be a part of the main site as it's built.

**Comment by aeolianeth** [comment]
@jmilldotdev awesome no worries, lets def revisit it if needed 🙏

**Comment by jmilldotdev** [comment]
Re-opening as it seems JBX wants to move on this feature soon. @aeolianeth please review?

**Comment by aeolianeth** [comment]
> Re-opening as it seems JBX wants to move on this feature soon. @aeolianeth please review?

Sounds good. Maybe we can chat about this in Peel townhall tomorrow? Wanna make sure we on same page 🙏

**Comment by jmilldotdev** [comment]
yup i'll be there

**Pull request closed without merging**
