### PR TITLE
Fixed bad spacing on pay input when usd is selected

### PR DESCRIPTION
**Pull request by NakedFool**
## What does this PR do and why?

Link to an issue - https://github.com/jbx-protocol/juice-interface/issues/1687

This PR solves bad spacing issue on pay input when USD is selected

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [x] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by johnnyd-eth** [comment]
Nice pickup @NakedFool! One extra fix would be nice:

Screen Shot 2022-08-12 at 11 36 29 am

Could we get the 'Paid as __' lined up properly with everything else?

**Comment by NakedFool** [comment]
> Nice pickup @NakedFool! One extra fix would be nice:
> 
> Screen Shot 2022-08-12 at 11 36 29 am
> 
> Could we get the 'Paid as __' lined up properly with everything else?

good catch! I've pushed fix and updated branch with `main`

**Comment by johnnyd-eth** [comment]
> > Screen Shot 2022-08-12 at 11 36 29 am
> > Could we get the 'Paid as __' lined up properly with everything else?
> 
> good catch! I've pushed fix and updated branch with `main`

Awesome @NakedFool! Friendly bump to chuck a screenshot on simple fixes like this that don't require a thorough test :)

**Comment by NakedFool** [comment]
> 



> > > Screen Shot 2022-08-12 at 11 36 29 am
> > > Could we get the 'Paid as __' lined up properly with everything else?
> > 
> > 
> > good catch! I've pushed fix and updated branch with `main`
> 
> Awesome @NakedFool! Friendly bump to chuck a screenshot on simple fixes like this that don't require a thorough test :)

ofc! I will apply that habit to all future PRs 🍻 

image

**Review by johnnyd-eth — APPROVED** [review]
LGTM ser thank you for the screenshot 💪

**Pull request merged**
