### PR TITLE
AMM Price UX Improvements

### PR DESCRIPTION
**Pull request by WadeSellers**
## What does this PR do and why?

This PR helps clarify how much of each token will be exchanged within Juicebox and expresses the AMM dialog represents current 3rd party exchange rates as well. 

I added a "1" in front of the input token to help clarify the exchange rate. 

I added a header title to the AMM Prices dialog to help clarify the information given in the TokenAMMPriceRow data. I followed the translation guidelines for introducing a new string.

Discord discussions on the topic:
(opening discussion)
https://discord.com/channels/775859454780244028/864240636277293106/960883897388916826

Discussion of potential solution
https://discord.com/channels/775859454780244028/864240636277293106/960889276139196416

Thread then moved to #-front-end 
https://discord.com/channels/775859454780244028/942522503258054686/961003391046279208

## Screenshots or screen recordings

Image showing the Before
AMMDialog-before

Image showing the After
AMMDialog-after

## Acceptance checklist

- [X] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [X] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Comment by WadeSellers** [comment]
@aeolianeth I went back and updated the translation files per the suggestion in the linter error. I do see that the translations didn't fill in. They are all just blank strings. I see that occurs with many messages in those files. I wonder if my use of 3rd messed it up. 

I could research a bit and see if I could find contextual translations to fit but I'm unsure if I could have them all vetted by a real person for each language without reaching out to the public.

Let me know if I should take it that far and I'll see what I can do.

**Comment by aeolianeth** [comment]
@WadeSellers thanks again for this contribution! I'm happy with this improvement 💪 .

I would like to suggest a few styling changes and have prepared a patch with the changes. The patch does the following:

- adds a space after `1`, so it becomes `/1 ETH` instead of `/1ETH`
- uses a smaller font size for the `current 3rd party exchange rates` text.

Here is a comparison of the changes:

| before patch | after patch |
| --- | --- |
| Screen Shot 2022-04-08 at 11 58 38 am | Screen Shot 2022-04-08 at 11 54 23 am |


How to apply the patch:

1. Copy this diff to your clipboard.
    Hover over the diff to reveal a "Copy" button in the top-right corner of the diff.
1. In your terminal, apply the diff with the following command:
   ```
   pbpaste | git apply
   ```

Please review and apply the patch when you get a chance!

If you have any trouble with this, let me know and I'll commit the changes for you if you agree with them.

```diff
diff --git a/src/components/shared/AMMPrices/TokenAMMPriceRow.tsx b/src/components/shared/AMMPrices/TokenAMMPriceRow.tsx
index a9b3bacc..d2efef5c 100644
--- a/src/components/shared/AMMPrices/TokenAMMPriceRow.tsx
+++ b/src/components/shared/AMMPrices/TokenAMMPriceRow.tsx
@@ -82,7 +82,7 @@ export default function TokenAMMPriceRow({
             overlayInnerStyle={{ ...fontStyle }}
           >
             <ExternalLink href={exchangeLink} style={{ fontWeight: 400 }}>
-              {`${formattedNum(WETHPrice)} ${tokenSymbol}/1ETH`}
+              {`${formattedNum(WETHPrice)} ${tokenSymbol}/1 ETH`}
               <LinkOutlined style={{ marginLeft: '0.2rem' }} />
             </ExternalLink>
           </Tooltip>
diff --git a/src/components/shared/AMMPrices/index.tsx b/src/components/shared/AMMPrices/index.tsx
index 453ac87c..79562341 100644
--- a/src/components/shared/AMMPrices/index.tsx
+++ b/src/components/shared/AMMPrices/index.tsx
@@ -33,7 +33,7 @@ export default function AMMPrices({
 
   return (
     <div style={{ ...style }}>
-      <p>
+      <p style={{ fontSize: '0.7rem' }}>
         <Trans>Current 3rd Party Exchange Rates</Trans>
       </p>
       <TokenAMMPriceRow
diff --git a/src/components/shared/inputs/Pay/PayInputSubText.tsx b/src/components/shared/inputs/Pay/PayInputSubText.tsx
index 8db0aae8..03b44be5 100644
--- a/src/components/shared/inputs/Pay/PayInputSubText.tsx
+++ b/src/components/shared/inputs/Pay/PayInputSubText.tsx
@@ -91,7 +91,7 @@ export default function PayInputSubText({
       plural: receivedTickets !== '1',
     })
 
-    return `${receivedTickets} ${tokenReceiveText}/1${currencyMetadata[payInCurrency]?.name}`
+    return `${receivedTickets} ${tokenReceiveText}/1 ${currencyMetadata[payInCurrency]?.name}`
   }, [
     converter,
     payInCurrency,

```

**Comment by WadeSellers** [comment]
Looks good @aeolianeth. I also had that space between the number and the currency unit as well but took it out. I'm happy with it in if you are. Patch applied and pushed up.

**Review by aeolianeth — APPROVED** [review]
@WadeSellers thanks for applying the patch!

The [Fleek preview](https://bafybeiduxluem45cmvqjf32aw3hq2rytrnhpk6vyeiw5gfh7odnxttin74.on.fleek.co/#/p/juicebox) LGTM, approving and merging 🚀

**Pull request merged**
