### PR TITLE
[BUG] Fix bug and bugishes in Pay modal

### PR DESCRIPTION
**Pull request by johnnyd-eth**
## What does this PR do and why?

1. Bug caused by translations

Screen Shot 2022-01-15 at 1 01 30 pm

2. Prevents user from opening pay modal when amount is 0

3. Removes 'To: ' in modal when wallet not connected yet

Screen Shot 2022-01-15 at 1 51 54 pm

4. Marks a few translations

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](../../CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](../../CONTRIBUTING.md#browser-support).

### CODE REVIEW

**Comment by aeolianeth** [comment]
@johnnyd-eth don't forget `yarn i18n:extract` 😉

**Comment by johnnyd-eth** [comment]
> @johnnyd-eth don't forget `yarn i18n:extract` 😉

Ah yep I forgot, thanks!

**Comment by aeolianeth** [comment]
@johnnyd-eth thanks - might be best to wait for https://github.com/jbx-protocol/juice-interface/pull/373 to merge as it contains the up-to-date translation source file.

**Comment by aeolianeth** [comment]
@johnnyd-eth, I made a boo-boo - see https://github.com/jbx-protocol/juice-interface/pull/373#issuecomment-1013631865

**Review by peripheralist — APPROVED** [review]

**Pull request merged**
