### PR TITLE
Auto Import Organise - Remove import order eslint plugin rule (1/n)

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

This PR is part of a greater stack:
- Adding support for a Prettier Plugin that automatically organises imports

This PR:
- Removes import rules from eslint.

## Screenshots or screen recordings

N/A

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [x] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1793** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1793" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1793?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]

**Comment by tomquirk** [comment]
Looks good although curious the build is failing

**Comment by tomquirk** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1793?utm_source=stack-comment).


Job Reference: KWKGYGFmwm3B0xgybjZV

**Comment by tomquirk** [comment]
**Graphite Merge Job**

Current status: 🔄 Waiting for checks to pass

This pull request is currently waiting for CI and mergeability checks to pass before being merged.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1793?utm_source=stack-comment).


Job Reference: qaXznWty1iJwzVy8ztWO

**Pull request merged**
