### PR TITLE
move all pages

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

Use the following script to rename:
```bash
#!/bin/bash

# Ensure a directory is passed as an argument
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <directory>"
    exit 1
fi

DIRECTORY=$1

find "$DIRECTORY" -type f -name '*.page.*' | while read -r file; do
    # Extract the base file name (excluding the path)
    base_name=$(basename "$file")

    # Extract the parts using a regex
    if [[ $base_name =~ (.*)\.page\.(.*) ]]; then
        prefix="${BASH_REMATCH[1]}"
        suffix="${BASH_REMATCH[2]}"

        # Form the new file name
        new_name="$prefix.$suffix"

        # Get the directory path
        dir_name=$(dirname "$file")

        # Rename the file
        mv "$file" "$dir_name/$new_name"
        echo "Renamed $file to $dir_name/$new_name"
    fi
done

```

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] (if relevant) I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] (if relevant) I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3977** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3977" target="_blank">Graphite</a> 
    * **PR #3978** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3978" target="_blank">Graphite</a> 
      * **PR #3979** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3979" target="_blank">Graphite</a> 
        * **PR #3980** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3980" target="_blank">Graphite</a> 
          * **PR #3981** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3981" target="_blank">Graphite</a> 
            * **PR #3982** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3982" target="_blank">Graphite</a> 
              * **PR #3983** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3983" target="_blank">Graphite</a> 
                * **PR #3984** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3984" target="_blank">Graphite</a> 
                  * **PR #3985** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3985" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3985?utm_source=stack-comment).

**Review by johnnyd-eth — APPROVED** [review]
Thic. Tested briefly and looks all good! Take this as approving the whole stack 🙏

**Comment by wraeth-eth** [comment]
@wraeth-eth started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3985).

**Comment by wraeth-eth** [comment]
[Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3985) rebased this pull request as part of a merge.

**Comment by wraeth-eth** [comment]
@wraeth-eth merged this pull request with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3985).

**Pull request merged**
