### PR TITLE
feat: require payment notice assent; redemption compliance assent

### PR DESCRIPTION
**Pull request by filipviz**
image

On payments:
1. Rename "Message from..." to "Notice from..." matching the language in the create flow.
2. Require explicit consent from users: "I understand and accept this project's notice."

image

On redemption:
1. Require explicit agreement from users: "I confirm that the use and redemption of crypto tokens is legal in my jurisdiction, and that I am fully responsible for compliance with all relevant laws and regulations."

### CODE REVIEW

**Comment by peripheralist** [comment]
cool cool cool @filipviz 

i'm down with accepting the legal disclaimer on the redeem modal, but what's the motivation for accepting the project notice?

**Comment by filipviz** [comment]
@peripheralist This was a suggestion from Rob – my understanding is that explicit consent (clicking a box saying you agree) is legally stronger than this type of workaround:

image

**Comment by peripheralist** [comment]
Yeah that makes sense. Just wondering if the motive is to help projects or jb, but cool with it either way

**Comment by filipviz** [comment]
The main motive for the redemption checkbox is to help JB. The main motive for the pay checkbox is to help projects. This allows projects to form agreements with people who pay their projects, and won't increase friction in most cases (since most projects don't use a pay notice).

**Comment by wraeth-eth** [comment]
Hey @filipviz , thanks for this one! From a design cohesive POV, could we wrap the checkbox in a Callout.Info, similar to what is seen in `src/components/Create/components/pages/ReviewDeploy/ReviewDeployPage.tsx`

**Review by wraeth-eth — APPROVED** [review]

**Pull request merged**
