### PR TITLE
feat: add notification page with formatting. No logic yet [4/n]

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

_Provide a description of what this PR does. Link to any relevant GitHub issues, Notion tasks or Discord discussions._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] (if relevant) I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] (if relevant) I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3335** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3335" target="_blank">Graphite</a> 
    * **PR #3336** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3336" target="_blank">Graphite</a> 
      * **PR #3337** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3337" target="_blank">Graphite</a> 
        * **PR #3342** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3342" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3342?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]

**Comment by wraeth-eth** [comment]
@wraeth-eth queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3342).

**Comment by wraeth-eth** [comment]
[Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3342) rebased this pull request as part of a merge.

**Comment by wraeth-eth** [comment]
@wraeth-eth merged this pull request with [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3342).

**Pull request merged**
