### PR TITLE
Cleanup quick project search

### PR DESCRIPTION
**Pull request by peripheralist**
## What does this PR do and why?

Improvements to the quick project search menu:
- debounce search input. wait 250 millis after typing to run search
- cleanup timeouts
- better cmd + k shortcut performance using "keydown" event
- add a "no results" message to empty search results state

## Screenshots or screen recordings

_If applicable, provide screenshots or screen recordings to demonstrate the changes._

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by peripheralist** [comment]
@wraeth-eth i saw that you opened another similar PR. does this accomplish the same thing?

**Comment by wraeth-eth** [comment]
> 

it does - shit sorry I merged the other one 😳
@peripheralist

**Review by wraeth-eth — APPROVED** [review]
LOVE

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #2653** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2653" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/2653?utm_source=stack-comment).

**Pull request merged**
