### PR TITLE
Auto Import Organise - Apply prettier rule (3/n)

### PR DESCRIPTION
**Pull request by wraeth-eth**
## What does this PR do and why?

This PR is part of a greater stack:
- Adding support for a Prettier Plugin that automatically organises imports

This PR:
- Applying new import rules to code.

## Screenshots or screen recordings

N/A

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [x] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #1793** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1793" target="_blank">Graphite</a> 
    * **PR #1794** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1794" target="_blank">Graphite</a> 
      * **PR #1795** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1795" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1795?utm_source=stack-comment).

**Review by tomquirk — APPROVED** [review]

**Comment by tomquirk** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1795?utm_source=stack-comment).


Job Reference: KWKGYGFmwm3B0xgybjZV

**Comment by tomquirk** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1795?utm_source=stack-comment).


Job Reference: qaXznWty1iJwzVy8ztWO

**Comment by tomquirk** [comment]
**Graphite Merge Job**

Current status: ⏳ Queued to merge

This pull request is currently queued to be merged as part of a stack.

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/1795?utm_source=stack-comment).


Job Reference: Ww7M8ZiVkvUteG4ABUOH

**Pull request merged**
