### PR TITLE
Feat: Upgrade react-scripts

### PR DESCRIPTION
**Pull request by sticklo**
## What does this PR do and why?

This PR upgrades to react-scripts@5.0.0, to take advantage of bundle size optimizations and faster compile times offered by Webpack 5 

## Screenshots or screen recordings

image

## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Comment by aeolianeth** [comment]
@sticklo thanks for looking into this!

I tried running locally but am getting this error. Are you getting the same error?

I imagine there will be a few of these that we need to iron out before this is ready to go - let me know how you go.


Screen Shot 2022-04-09 at 10 25 11 pm

I also retargetted this PR at the `main` branch:

Screen Shot 2022-04-09 at 10 26 34 pm

**Comment by sticklo** [comment]
oh wow, It works well on my end here. 
what do you suggest we do about it now ?

**Comment by aeolianeth** [comment]
> oh wow, It works well on my end here. what do you suggest we do about it now ?

@sticklo 

The build is also failing https://github.com/jbx-protocol/juice-interface/pull/777/checks?check_run_id=5957289377.

I would try deleting node modules folder `rm -Rf node_modules`, and `yarn install`ing from scratch.

**Comment by sticklo** [comment]
let me try that now thank you @aeolianeth

**Pull request closed without merging**
