### PR TITLE
Use new library to better handle number inputs with decimals

### PR DESCRIPTION
**Pull request by torvusbug**
## What does this PR do and why?

I found it slightly difficult to use some of the number inputs. To fix it, I'm using a new library [react-number-format](https://www.npmjs.com/package/react-number-format) to handle it.

## Screenshots or screen recordings

https://user-images.githubusercontent.com/4457995/148684073-41079b20-2383-4f42-999f-b56738427ed9.mp4

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](../../CONTRIBUTING.md#approval-guidelines) for this PR.
- [x] I have tested this PR in [all supported browsers](../../CONTRIBUTING.md#browser-support).

### CODE REVIEW

**Comment by peripheralist** [comment]
Great stuff. No idea why I didn't start out using a library like this 😅

Only issue I see is that the input breaks when its value is just `.`—i.e. if typing `.5` without a leading zero it breaks after typing the decimal. Looks solid otherwise!

**Comment by aeolianeth** [comment]
@torvusbug ohh, wow, this is awesome <3.

We may need to wait for https://github.com/jbx-protocol/juice-interface/pull/313 to merge as I believe it touches these number inputs.

Also curious about the weight the new dep adds to our bundle - want to run a `yarn analyze`?

**Comment by peripheralist** [comment]
are we feeling good about adding this new dependency @aeolianeth @torvusbug ?

also, could we be replacing other instances of the `formattedNum()` util with this? (can be a separate PR)

**Comment by torvusbug** [comment]
@peripheralist I'm trying to fix your discovered bug where ".5" creates a runtime error. There are other number-only inputs I've tried to replace with this but ran into state issues. I'll try to solve some of these and see how far I can get before moving this PR forward.

**Comment by aeolianeth** [comment]
> are we feeling good about adding this new dependency @aeolianeth @torvusbug ?
> 
> also, could we be replacing other instances of the `formattedNum()` util with this? (can be a separate PR)

Yep, feeling real good about this, thanks again @torvusbug. Still curious about the added bundle size, but can't imagine it would be a blocker.

**Comment by torvusbug** [comment]
@aeolianeth I'll close this for now and reopen when I think it's ready. There's still a runtime bug when typing ".5" instead of "0.5". Something to do with how one of the libraries parses ".5".

**Pull request closed without merging**
