### PR TITLE
feat! re-order create navbar

### PR DESCRIPTION
**Pull request by wraeth-eth**
## Acceptance checklist

- [ ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).
- [ ] I have tested this PR in dark mode and light mode (if applicable).

### CODE REVIEW

**Comment by wraeth-eth** [comment]
Current dependencies on/for this PR:
* main
  * **PR #3099** <a href="https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3099" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/jbx-protocol/juice-interface/3099?utm_source=stack-comment).

**Comment by tomquirk** [comment]
@wraeth-eth can we get @strath-m UX approval for this one?

**Comment by strath-m** [comment]
I see the reasoning behind it but I much prefer 'Create a project' as a direct CTA over 'Create' (which is ambiguous). I also think its better to have the 2 most important actions on either end of the links for maximum visibility. I see there is a bit of a clash where it says 'Create a project' twice but I don't think it's a major issue. @wraeth-eth @tomquirk

**Comment by tomquirk** [comment]
will close for now 🙏

**Pull request closed without merging**
