### PR TITLE
Relocate component files

### PR DESCRIPTION
**Pull request by aeolianeth**
## What does this PR do and why?

Another step towards V2.

This PR attempts to establishes a clearer component file hierarchy. The goal: make it easier to identify where components are being used. Outside of general housekeeping, this will hopefully ease the V2 planning process as we can more easily identify interdependencies between components.

 The following changes have been made:
- **Create a `components/Project/` directory**. 
   The `Project` component is used in both the Dashboard and Create page, so I felt it made sense for it to have its own directory. This means we can have a `V1Project` and `V2Project`, for example.
- **Move Project-specific modals to `components/Project/modals`**.
    These modals aren't shared with any other page.
- **Move Funding cycle-specific modals to `components/FundingCycle/modals`**.
   Same as above.
- **Move forms from `Create/` into `shared/forms/` directory**.
   These forms are shared with the Project page
- **Move `Dashboard/ReservedTokens`, `Dashboard/Spending` and `Dashboard/FundingHistory` to `FundingCycle/`**.
   These components are only used by `FundingCycle/` components.
- **Delete `src/components/modals/ConfirmStakeTokensModal.tsx`**
   Don't think it's being used.

## Acceptance checklist

- [x] I have evaluated the [Approval Guidelines](../CONTRIBUTING.md#approval-guidelines) for this PR.
- [-] I have tested this PR in [all supported browsers](../CONTRIBUTING.md#browser-support).

### CODE REVIEW

**Comment by aeolianeth** [comment]
@peripheralist I started to have a bit of scope-creep here but I think this PR is still small enough for review. Let me know what you think! 

cc @johnnyd-eth

**Comment by torvusbug** [comment]
I like this reorganization, it's like pulling off a band-aid: you have to do it but there's rarely an "appropriate" time to do it so just pull it off now while you're thinking about it.

**Comment by peripheralist** [comment]
love how you're thinking about this @aeolianeth . some tidying up is definitely needed (with or without prepping for v2) and this strategy makes sense to me.

there's some conflicts but approving for now

**Review by peripheralist — APPROVED** [review]

**Comment by aeolianeth** [comment]
Thanks for the review @torvusbug @peripheralist!

Thinking I might leave this PR open so that we can merge Trending Projects first. I fear the conflicts that we'd create for the trending projects branch 😂

**Comment by aeolianeth** [comment]
@peripheralist, conflicts resolved! 🏓

**Pull request merged**
