### PR TITLE
[899] Label overflowing on "add to balance" input 

### LINKED ISSUE #899: Label overflowing on "add to balance" input
## Summary

`Payout amount` label is overflowing

It also should say "Pay amount" instead.

Screen Shot 2022-05-02 at 5 48 47 am

## Steps to reproduce

On a project you own (or in dev):

1. Go to `Tools` drawer by clicking the wrench in the top-right.
2. Observe.

### PR DESCRIPTION
**Pull request by jmilldotdev**
## What does this PR do and why?

Closes #899 partially. To truly solve label overlap in a columnar form, we should bump antd to 4.18.0+ to use the labelWrap property in the form API though

## Screenshots or screen recordings

image

## Acceptance checklist

- [ x ] I have evaluated the [Approval Guidelines](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#approval-guidelines) for this PR.
- [ x ] I have tested this PR in [all supported browsers](https://github.com/jbx-protocol/juice-interface/blob/main/CONTRIBUTING.md#supported-browsers).

### CODE REVIEW

**Comment by johnnyd-eth** [comment]
Nice one @jmilldotdev! Merging.

Perhaps we could add a housekeeping issue for bumping antd to 4.18.0+?

**Comment by johnnyd-eth** [comment]
Nice wording change @jmilldotdev . Perhaps we could just solve this problem by having the label on top of the input like it most other places throughout the app, like so: 

Screen Shot 2022-05-02 at 11 34 50 pm

Also, good call about bumping the antd version - perhaps we could make a housekeeping issue for this?

**Comment by jmilldotdev** [comment]
Okay, I changed the forms to vertical to be consistent with other drawer forms.

**Review by johnnyd-eth — APPROVED** [review]
LGTM, v nice

**Pull request merged**
